parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
env:
  browser: true
  node: true
plugins:
  - 'react'
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
settings:
  react:
    version: 'detect'
ignorePatterns:
  - 'pages/blog/**/*.tsx'
rules:
  react/prop-types: 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
