version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.14
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package.json" }}
            - v1-node-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  deploy:
    docker:
      - image: circleci/python:3.7-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - restore_cache:
          keys:
            - v1-python-dependencies-{{ checksum "Pipfile" }}
            - v1-python-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          paths:
            - .venv
          key: v1-python-dependencies-{{ checksum "Pipfile" }}
      - run: pipenv run yarn build
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: workspace
