version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package.json" }}
            - v1-node-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  build_and_deploy:
    docker:
      - image: circleci/node:12
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn build
      - run: bash .circleci/deploy.sh
workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only: workspace
